language: python

jobs:
  include:
    - python: "3.7"
      env: INTEGRATION=true
    - python: "3.8"
    - python: "3.7"
    - python: "3.6"
    - python: "3.5"

# for docker build
env:
- alpine_version=alpine3.10 debian_version=buster
- secure: "oY8Ir2Yykb1hspxxhrfktAJlPmjkGlSHg7tCVCq+jWZ1ZoyTSyR7hY3UCz0QUMG5Kug5AMp5kGXIxE+7nFbK5k0jGk+Vhd0v5AxDf+Q0JouK57ONEQE30rSXtBlJMTpRInI45/6qbszMI3SEIhunBRt5y335uCs80+ZeqDXjc710q4SZR+Q6dCU6K0d0ayRS4eFVROctUQjTv+oWvqx0pevAeOqJklscVyzdKwpf0QijMp7tRrMrqw0e4fT9zqIMObSRt8jE/3tzDGBFQq71iOEZ6RLAYInhXWp5wAtN6RAjind2vTIH9pOfh487fE7YkJL8C4Uhhb91yxN44UYdT6pJ9fvm/6/eI9gx/7pWCVacnv3Zxwkp1n2HKvPfUwAosnKgd75BpfgBfjOdqCgDFfaxamL7f7i3Xt8Hz2LsTGSXq8A6gem7WyVn+O3hBuF8eGKeJDzmf8QFaKmhAcRgZFJ6PTvpjPGSvUvrTkYVF99ejiQtDg1/DFTsxr1P4ayV9ESl4DbUV/7udz6Nm7m7TT7mV4VIvsHcVNYAAdYMNg3E8EOdvmf0Fx1lB/8FQDGpN6iNviYr/IZoV9LXcUSt5B8YhpMXJtx4dKDmM/AZtf/XKo/LkCHbYZIE5VmTtAXpj51WcO8Fv4cfOthCGlSQPiCKaJyiUx/1BafNRlh1f/E="
- secure: "AG31O8hZ8lcNy4KZNz+lOD263dP6bUc6L++NDuaQ+OEztdLNt38+rs7XidynXvSVdzoXgtH4tzPZAMeU84jPu0bYy+8FZi7LRMB9YPqbNQSuN4iCaMUgbKlasIuLlQQ3jeZiR6jR1KHelo2bc4vELUxqpGB0k8L8lqgw0DmTZGGJt+LkhVDlt9Di4I/J7WCYrzxf4uG0q/CT6xAXmY3nOSWVOam84NUDjVdrtZcKjqdNC1Bm44HE2F/fG/YpcHPARW9WOUtv4pcvic7+bbp3AGvX7VwykuCvzM46PQiTVSJGXFMZn1R2Mxfjp+a1vFqwcZAIe9FOiWyr2YvY5GeWMtHSAnyGvLTAurocRZ8gvBUylgXGwfJqTz1zHvPmAFk/d3Te5PPKG3hA27ssbK1rIi51RybZzU4T2CvMAF6gbVIWgiTeZII41iG+Wm5CQI5RmjSdLKzNBZdi/PFn52Cj6tzLYmXKyMAYcVFmRDE7D/cC5CV//8ShnU37BFWZ79IlGuD4PWyvTbqfNvgQcrCrARYiUmrmoOZ3fZCkdHd5sAH/bfq7AUR3crFyNhX1DrON/K7kc+u7ADbsk3AjjRchD56XlQFCA2ZLf06HvuD+RkhzRVpNT+X6Vtl7bPcM0yb3HMCK5crB4h+fu8nk6XALRcen7/RUGBr8b+3kw//mgrA="

services:
- docker

install:
- sudo apt-get -y install pandoc
- pip install pypandoc
- python setup.py develop

before_script:
- if [[ -n INTEGRATION ]] ; then bash run_gitlab_in_docker.sh ; fi
- if [[ -n INTEGRATION ]] ; then export GITLAB_URL=$(cat gitlab_url.txt) ; fi
- if [[ -n INTEGRATION ]] ; then export GITLAB_TOKEN=$(cat gitlab_token.txt) ; fi

script:
# unit tests
- if [[ -z INTEGRATION ]] ; then py.test --ignore gitlabform/gitlabform/test ; fi
# integration tests
- if [[ -n INTEGRATION ]] ; then py.test gitlabform/gitlabform/test ; fi

deploy:
- provider: pypi
  user: python-egnyte
  password:
    secure: "DxUicAiXMUmoS0h5YYfGhcjeOvf5aPACN/ljn6GITR0MtoLFzRrmuuNPHuAseNbu8Q7fOcGVQ9ez6tQhGrjY0wzjSQmWIsSX9kez1OiVNrGDRKoKKLmfkxAO6mRU9GHOYT65mKQAW8Mdl14j9X1CxyO5qYb9CrmPCXCFQq8Bp45t1sTv1hypZpSJtrc5JUy8FymOFbI65nitr9wf3aWWMCS1Tv7JdpottiQ3OtmqYzvpRzbymDWcn2P8WX0nfrPTPaqJdt1wz+nzOusxj0SIO4LTPx0CjdALLNJqF9w9CZUvln93ZToIdwMLYPjWQ59WF7Mb42chTCABtLgetkl6qy9GFZtGauoeF9S3vnU7GT3lFVDTCVQeaAo5+nUvIbcj7NnBZipsEa+Cnv6Ijfrh4eEf7JMbnGuUl5rv6vxUl1t+uGMoWjDfHMPE9DvwzVg3AsPpyeu+olTY7xMDZ/47sR4/likTzeamGNL7cuj7BknkVSIH+wAbWpU9v5zctStNs3vPJX2gNdawsumsVZbAPm+6JeItt+bVWGcJEd6XfluNUFxj61YnYAi9QVj3L0lYPRRRa7LKP1ryDBwWeP4vUYdLhGj5qPTzN4HVJAN8bWGehaWK9f57DuuKvRw7V5vXkTRM5loRz0lziaWkUmew9sK3asw1jMC0uYsVak/us50="
  distributions: "sdist bdist_wheel"
  on:
    repo: egnyte/gitlabform
    tags: true
    python: "3.7"
  before_deploy:
  - "pip install pypandoc"

- provider: script
  on:
    repo: egnyte/gitlabform
    tags: true
    python: "3.7"
  before_deploy:
  - bash build_docker_images.sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script: PUSH_IMAGES=true bash build_docker_images.sh
